[project]
name = "readboard"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12, <3.13"
dependencies = [
    "pillow>=11.3.0",
    "pyperclip>=1.9.0",
    "pytesseract>=0.3.13",
]
