[project]
name = "readboard"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12, <3.13"
dependencies = [
    "opencv-python>=4.12.0.88",
    "pyperclip>=1.9.0",
    "pyscreenshot>=3.1",
    "pytesseract>=0.3.13",
]
